name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt -t lambdas/common

      - name: Package Lambda functions
        run: |
          cd lambdas/authorizer
          zip -r ../../authorizer.zip *
          cd ../wrapped
          zip -r ../../wrapped.zip *
          cd ../release_radar
          zip -r ../../release_radar.zip *
          cd ../update_user_table
          zip -r ../../update_user_table.zip *
          cd ../wrapped_email
          zip -r ../../wrapped_email.zip *
          cd ../release_radar_email
          zip -r ../../release_radar_email.zip *
          cd ../..
          mkdir -p python/lambdas
          cp -r lambdas/common python/lambdas/
          python3.10 -m pip install --platform manylinux2014_x86_64 --only-binary=:all: -t python/ -r requirements.txt
          zip -r xomify-shared-packages.zip python

      - name: Deploy Lambda Layer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          LAYER_OUTPUT=$(aws lambda publish-layer-version \
            --layer-name xomify-shared-packages \
            --zip-file fileb://xomify-shared-packages.zip \
            --compatible-runtimes python3.10 \
            --region $AWS_REGION \
            --output json)

          echo "LAYER_ARN=$(echo $LAYER_OUTPUT | jq -r .LayerVersionArn)" >> $GITHUB_ENV
          echo "Layer ARN: $LAYER_ARN"

      - name: Deploy Authroizer Lambda Function Code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          aws lambda update-function-code \
            --function-name xomify-authorizer \
            --zip-file fileb://authorizer.zip
          sleep 5

      - name: Deploy Authorizer Lambda Configurations
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          LAYER_ARN: ${{ env.LAYER_ARN }}
        run: |
          aws lambda update-function-configuration \
            --function-name xomify-authorizer \
            --layers $LAYER_ARN \
            --region $AWS_REGION

      - name: Deploy Wrapped Lambda Function Code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          aws lambda update-function-code \
            --function-name xomify-wrapped \
            --zip-file fileb://wrapped.zip
          sleep 5

      - name: Deploy Wrapped Lambda Configurations
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          LAYER_ARN: ${{ env.LAYER_ARN }}
        run: |
          aws lambda update-function-configuration \
            --function-name xomify-wrapped \
            --layers $LAYER_ARN \
            --region $AWS_REGION

      - name: Deploy Release Radar Lambda Function Code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          aws lambda update-function-code \
            --function-name xomify-release-radar \
            --zip-file fileb://release_radar.zip
          sleep 5

      - name: Deploy Release Radar Lambda Configurations
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          LAYER_ARN: ${{ env.LAYER_ARN }}
        run: |
          aws lambda update-function-configuration \
            --function-name xomify-release-radar \
            --layers $LAYER_ARN \
            --region $AWS_REGION

      - name: Deploy Update User Table Lambda Function Code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          aws lambda update-function-code \
            --function-name xomify-update-user-table \
            --zip-file fileb://update_user_table.zip
          sleep 5

      - name: Deploy Update User Table Lambda Configurations
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          LAYER_ARN: ${{ env.LAYER_ARN }}
        run: |
          aws lambda update-function-configuration \
            --function-name xomify-update-user-table \
            --layers $LAYER_ARN \
            --region $AWS_REGION

      - name: Deploy Wrapped Email Lambda Function Code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          aws lambda update-function-code \
            --function-name xomify-wrapped-email \
            --zip-file fileb://wrapped_email.zip
          sleep 5

      - name: Deploy Wrapped Email Lambda Configurations
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          LAYER_ARN: ${{ env.LAYER_ARN }}
        run: |
          aws lambda update-function-configuration \
            --function-name xomify-wrapped-email \
            --layers $LAYER_ARN \
            --region $AWS_REGION

      - name: Deploy Release Radar Email Lambda Function Code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          aws lambda update-function-code \
            --function-name xomify-release-radar-email \
            --zip-file fileb://release_radar_email.zip
          sleep 5

      - name: Deploy Release Radar Email Lambda Configurations
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          LAYER_ARN: ${{ env.LAYER_ARN }}
        run: |
          aws lambda update-function-configuration \
            --function-name xomify-release-radar-email \
            --layers $LAYER_ARN \
            --region $AWS_REGION
